name: Build and Push Docker Images

on:
  push:
    branches: [ main, dev, templating ]
    paths:
      - 'consumer/**'
      - 'producer/**'
      - '.github/workflows/docker-build.yml'

# Add these permissions
permissions:
  contents: read
  packages: write    # This is required to push to ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [consumer, producer]
        include:
          - service: consumer
            dockerfile: consumer/Dockerfile
            image: akkt1-g1-consumer
          - service: producer
            dockerfile: producer/Dockerfile
            image: akkt1-g1-producer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USR }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/MCCE2024/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=sha,format=short
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 